# -*- coding: utf-8 -*-
"""densenet (prova 1)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15mLGZUrnWTMAYUfYrQu3klbRTHeJstjQ
"""

from google.colab import drive
import os
import h5py
import numpy as np
import tensorflow as tf
from tensorflow.keras import layers, models, callbacks, regularizers, applications
import matplotlib.pyplot as plt
from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay, roc_curve, auc

if not os.path.exists('/content/drive'):
    drive.mount('/content/drive')

# --- FILE PREPARATION  ---
!rm -rf /content/*.h5
for f in ['train_x','train_y','valid_x','valid_y','test_x','test_y']:
    src = f"/content/drive/MyDrive/PCam/camelyonpatch_level_2_split_{f}.h5"
    if os.path.exists(src):
        !cp "$src" /content/
print("Files ready on the local disk")

np.random.seed(42)
tf.random.set_seed(42)

# --- UPLOAD OF DATA ---
def load_to_ram(x_path, y_path, num_samples=80000):
    with h5py.File(y_path, 'r') as fy:
        y_all = fy['y'][:num_samples].reshape(-1, 1).astype('float32')
    with h5py.File(x_path, 'r') as fx:
        x_all = fx['x'][:num_samples]
    return x_all, y_all

X_train, Y_train = load_to_ram('/content/camelyonpatch_level_2_split_train_x.h5',
                                    '/content/camelyonpatch_level_2_split_train_y.h5', 80000)
X_val, Y_val = load_to_ram('/content/camelyonpatch_level_2_split_valid_x.h5',
                                    '/content/camelyonpatch_level_2_split_valid_y.h5', 8000)

# --- DATA AUGMENTATION ---
def augment(image, label):
    image = tf.image.resize_with_crop_or_pad(image, 96, 96)
    image = tf.cast(image, tf.float32)
    image = applications.densenet.preprocess_input(image)

    image = tf.image.random_flip_left_right(image)
    image = tf.image.random_flip_up_down(image)
    image = tf.image.random_brightness(image, 0.15)
    image = tf.image.random_contrast(image, lower=0.75, upper=1.25)
    return image, label

def process_val(image, label):
    image = tf.image.resize_with_crop_or_pad(image, 96, 96)
    image = tf.cast(image, tf.float32)
    image = applications.densenet.preprocess_input(image)
    return image, label

# Funzione per mappare solo le immagini nel generatore di test dello streaming
def process_test_img(image):
    image = tf.image.resize_with_crop_or_pad(image, 96, 96)
    image = tf.cast(image, tf.float32)
    image = applications.densenet.preprocess_input(image)
    return image

# --- TRANSFER LEARNING ARCHITECTURE ---
tf.keras.mixed_precision.set_global_policy('mixed_float16')

def build_transfer_model():
    base_model = applications.DenseNet121(weights='imagenet', include_top=False, input_shape=(96, 96, 3))
    base_model.trainable = True
    for layer in base_model.layers[:-30]:
        layer.trainable = False

    model = models.Sequential([
        base_model,
        layers.GlobalAveragePooling2D(),
        layers.Dense(256, activation='relu', kernel_regularizer=regularizers.l2(1e-4)),
        layers.BatchNormalization(),
        layers.Dropout(0.5),
        layers.Dense(1, activation='sigmoid', dtype='float32')
    ])
    return base_model, model

base_model, model = build_transfer_model()

# --- TRAINING PHASE ---
BATCH_SIZE = 128

train_ds = tf.data.Dataset.from_tensor_slices((X_train, Y_train))\
    .shuffle(10000).map(augment, num_parallel_calls=tf.data.AUTOTUNE)\
    .batch(BATCH_SIZE).prefetch(tf.data.AUTOTUNE)

val_ds = tf.data.Dataset.from_tensor_slices((X_val, Y_val))\
    .map(process_val, num_parallel_calls=tf.data.AUTOTUNE)\
    .batch(BATCH_SIZE).prefetch(tf.data.AUTOTUNE)

print("\n--- Phase 1: Warm-up ---")
model.compile(optimizer=tf.keras.optimizers.Adam(1e-3),
              loss='binary_crossentropy',
              metrics=['accuracy', tf.keras.metrics.AUC(name='auc')])
model.fit(train_ds, validation_data=val_ds, epochs=3)

print("\n--- Phase 2: Fine-Tuning ---")
base_model.trainable = True
class_weights = {0: 1.0, 1: 2.5}
model.compile(optimizer=tf.keras.optimizers.Adam(1e-5),
              loss=tf.keras.losses.BinaryCrossentropy(label_smoothing=0.1),
              metrics=['accuracy', tf.keras.metrics.AUC(name='auc')],
              jit_compile=True)

history = model.fit(train_ds, validation_data=val_ds, epochs=25, class_weight=class_weights,
                    callbacks=[callbacks.EarlyStopping(monitor='val_auc', mode='max', patience=8, restore_best_weights=True),
                               callbacks.ReduceLROnPlateau(monitor='val_auc', mode='max', factor=0.5, patience=3, verbose=1)])

# PLOT OF FIGURES
plt.figure(figsize=(18,5))

# Loss Curve
plt.subplot(1,3,1)
plt.plot(history.history['loss'], label='Train Loss')
plt.plot(history.history['val_loss'], label='Val Loss')
plt.title("Loss"); plt.xlabel("Epochs"); plt.ylabel("Loss")
plt.ylim(0, 1.0); plt.legend()

# Accuracy Curve
plt.subplot(1,3,2)
plt.plot(history.history['accuracy'], label='Train Accuracy')
plt.plot(history.history['val_accuracy'], label='Val Accuracy')
plt.title("Accuracy"); plt.xlabel("Epochs"); plt.ylabel("Accuracy")
plt.ylim(0, 1.0); plt.legend()

plt.tight_layout()
plt.show()


# ---STREAMING EVALUATION ---
print("\n Final evaluation on test set ")

fx = h5py.File('/content/camelyonpatch_level_2_split_test_x.h5', 'r')
fy = h5py.File('/content/camelyonpatch_level_2_split_test_y.h5', 'r')

X_dataset = fx['x']
Y_test = fy['y'][:].reshape(-1, 1).astype('float32') 
num_test_samples = X_dataset.shape[0]

def test_generator():
    for i in range(num_test_samples):
        yield X_dataset[i]

test_ds = tf.data.Dataset.from_generator(
    test_generator,
    output_signature=tf.TensorSpec(shape=(96, 96, 3), dtype=tf.uint8)
)

test_ds = test_ds.map(process_test_img, num_parallel_calls=tf.data.AUTOTUNE).batch(BATCH_SIZE).prefetch(tf.data.AUTOTUNE)

# Probabilistic prediction 
y_pred_prob = model.predict(test_ds)

threshold = 0.35
y_pred = (y_pred_prob > threshold).astype(int)

print(f"\n--- Final report (Threshold: {threshold}) ---")
print(classification_report(Y_test, y_pred, target_names=["Healthy","Tumor"]))

# Confusion Matrix
cm = confusion_matrix(Y_test, y_pred)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=["Healthy","Tumor"])
disp.plot(cmap='Blues', values_format='d'); plt.show()

# ROC/AUC Curve
fpr, tpr, thresholds_roc = roc_curve(Y_test, y_pred_prob)
roc_auc = auc(fpr, tpr)

plt.figure(figsize=(8,6))
plt.plot(fpr, tpr, color="blue", lw=2, label="ROC curve (AUC = %0.4f)" % roc_auc)
plt.plot([0, 1], [0, 1], color="red", lw=2, linestyle="--")
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("Receiver Operating Characteristic (ROC) - Test Set")
plt.legend(loc="lower right")
plt.grid(True, linestyle='--', alpha=0.6)
plt.show()

fx.close()
fy.close()
print(f"Evaluation complete. Test HDF5 streams closed correctly. Final Test AUC: {roc_auc:.4f}")
